### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by nitori** [chireiden/shanghai#10]
I haven't added a license yet.

Should we go with GPLv3?

**Comment by FichteFoll** [comment]
I haven't used a copyleft license ever, so I'll need to consider this. Usually I stick with MIT because of the freedom it provides.

**Comment by knitori** [comment]
Missing copyright notice in every file.

**Comment by FichteFoll** [comment]
Probably helpful flake8 settings: https://github.com/The-Compiler/qutebrowser/blob/367063a776d2cda29a8fb3283a788e46349c600e/.flake8#L50-L52
