### ISSUE TITLE
Logging context doesn't really work with async tasks

### ISSUE THREAD

**Issue by knitori** [chireiden/shanghai#32]
I thought the concept Flask uses for their App and Request Context was a neat idea and wanted to use it here too, but in the end, I think it won't really work.

An example:

```python
from shanghai.logging import with_log_context
import asyncio

@with_log_context(lambda: LogContext('AAA', 'AAA'))
async def task_a():
    current_logger.debug('in task A (1)')
    await asyncio.sleep(3)
    current_logger.debug('in task A (2)')
    await asyncio.sleep(2)
    current_logger.debug('in task A (3)')

@with_log_context(lambda: LogContext('BBB', 'BBB'))
async def task_b():
    current_logger.debug('in task B (1)')
    await asyncio.sleep(2)
    current_logger.debug('in task B (2)')
    await asyncio.sleep(3)
    current_logger.debug('in task B (3)')

loop = asyncio.get_event_loop()
tasks = [
    asyncio.ensure_future(task_a()),
    asyncio.ensure_future(task_b()),
]
loop.run_until_complete(asyncio.wait(tasks))
```

`task_a` and `task_b` essentially behave like threads in this case. That would be fine, if they actually *were* threads, because that's what `logging.LocalStack` is for - a thread-local stack. But since we don't actually have threads here, all the tasks use the same stack, and don't have the same behaviour.

In the above example one might expect something like:
```
AAA/AAA […] DEBUG | in task A (1)
BBB/BBB […] DEBUG | in task B (1)
BBB/BBB […] DEBUG | in task B (2)
AAA/AAA […] DEBUG | in task A (2)
AAA/AAA […] DEBUG | in task A (3)
BBB/BBB […] DEBUG | in task B (3)
```
Where `AAA/AAA` and `BBB/BBB` denote the different logging context instances used. But the actual result is:
```
AAA/AAA DEBUG  | in task A (1)
BBB/BBB DEBUG  | in task B (1)
BBB/BBB DEBUG  | in task B (2)
BBB/BBB DEBUG  | in task A (2)
BBB/BBB DEBUG  | in task A (3)
BBB/BBB DEBUG  | in task B (3)
```
Which happens because the log context for `BBB/BBB` was the last one put onto the stack.

A big mistake on my part and needs to be changed into something more reliable.

**Comment by FichteFoll** [comment]
Tbh, I kind of expected this but for some reason it worked fine with multiple networks the last time I tried. No idea regarding a solution yet because we don't control the event loop.

What would certainly work however is getting rid of the proxy entirely and passing around logger objects instead. That's more verbose but involves less magic and actually works.
