### ISSUE TITLE
CTCP support

### ISSUE THREAD

**Issue by FichteFoll** [chireiden/shanghai#6]
- In core or as plugin? → core
- http://www.irchelp.org/irchelp/rfc/ctcpspec.html

**Comment by knitori** [comment]
Additional: It appears that most IRC clients don't even implement the full spec.

I was pointed to this: http://www.kvirc.net/doc/doc_ctcp_handling.html

So I think we should keep it to the basics.

**Comment by FichteFoll** [comment]
Considering ACTION is also a CTCP and quite commonly used, I'm unsure if this can be provided by a plugin without being "too mandatory", if you know what I mean.

Like, we'll certainly have a `msg` method of some sort that sends a message to some channel or user and having a `action` method next to it sounds very practical.

**Comment by knitori** [comment]
To answer the initial question, I think CTCP should be part of the core.

**Comment by FichteFoll** [comment]
Closed by #33 and #34.
